environment:
  matrix:
    - nodejs_version: "10"

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version
  - npm --version

test_script:
  - npm run review
  - npm run package
