// flow-typed signature: f5408158c3b1132828035a878b7cd6c7
// flow-typed version: <<STUB>>/lodash.clonedeep_v4.5.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.clonedeep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.clonedeep' {
  declare module.exports: {
    <T>(object: $Shape<T>): $Shape<T>
  }
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.clonedeep/index' {
  declare module.exports: $Exports<'lodash.clonedeep'>;
}
declare module 'lodash.clonedeep/index.js' {
  declare module.exports: $Exports<'lodash.clonedeep'>;
}
